### PR TITLE
Chore - use YAML build params

### PR DESCRIPTION
**Pull request by stijnmoreels**
Relates to https://github.com/arcus-azure/arcus/issues/88

### CODE REVIEW

**Comment by stijnmoreels** [comment]
Does the pipeline itself have to change? Or is the variable there required for this parameters to work?

**Comment by tomkerkhove** [comment]
Actually yes, sorry! See : https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cyaml-example#parameters

**Comment by stijnmoreels** [comment]
> Actually yes, sorry! See : https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cyaml-example#parameters

😅 'yes' the pipeline has to change or 'yes' the pipeline param there is required to work. I haven't found anything about this in the docs.

**Comment by tomkerkhove** [comment]
Yes you have to change it, the  YAML sample in the link shows how to consume it:
`  - script: echo The image parameter is ${{ parameters.image }}`

**Pull request merged**
