### PR TITLE
Remove the dependency to AspNetCore

### PR DESCRIPTION
**Pull request by fgheysels**
This PR is related to #189 

I've removed the dependencies to AspNetCore framework.

### CODE REVIEW

**Comment by fgheysels** [comment]
Woops, seems like I should've ran the testsuites before creating the PR :)

**Comment by tomkerkhove** [comment]
That's why we have them here, no worries!

Thanks and LGTM other than the test.

**Comment by fgheysels** [comment]
> That's why we have them here, no worries!
> 
> Thanks and LGTM other than the test.

I've updated the version of some packages, don't know if that might be an issue ? (2.2.0 > 3.1.8 for some extension packages)

**Comment by tomkerkhove** [comment]
No problem at all, thanks @fgheysels!

**Review by tomkerkhove — APPROVED** [review]

**Comment by fgheysels** [comment]
Thanks, now I can use Arcus.Security in a simple background service which runs as a container, on a base-image that does not contain the ASP.NET Core libraries / framework.

**Comment by tomkerkhove** [comment]
Thank you!

**Pull request merged**
