### PR TITLE
docs: add manual redirection page for az key vault auth

### PR DESCRIPTION
**Pull request by stijnmoreels**
Adds a manual page for the Azure Key Vault authentication mechanism for the Managed Identity (because other ways doesn't seem to be working).

Relates to #262

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Can you check if it's because we are missing this plugin?
https://github.com/jekyll/jekyll-redirect-from

This is what we use for AZUG - https://github.com/AzugBe/azugbe.github.io/blob/master/_posts/events/2020-08-19---playing-the-game-with-azure-cognitive-services.md

**Comment by stijnmoreels** [comment]
> Can you check if it's because we are missing this plugin?
> https://github.com/jekyll/jekyll-redirect-from
> 
> This is what we use for AZUG - https://github.com/AzugBe/azugbe.github.io/blob/master/_posts/events/2020-08-19---playing-the-game-with-azure-cognitive-services.md

Hmm, I added that plugin and that didn't work.

**Comment by tomkerkhove** [comment]
Locally or on GitHub Pages?

**Comment by stijnmoreels** [comment]
> Locally or on GitHub Pages?

Remote

**Review by tomkerkhove — APPROVED** [review]

**Pull request merged**
